# Generated by Django 3.2.8 on 2023-03-19 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatmessage_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='image',
            new_name='image_data',
        ),
    ]
